"""add faiss_ids column to documents

Revision ID: b859643aad53
Revises: ba7a5a281de8
Create Date: 2026-08-08 23:56:18.427555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b859643aad53'
down_revision: Union[str, Sequence[str], None] = 'ba7a5a281de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('faiss_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'faiss_ids')
    # ### end Alembic commands ###
