"""add process column to documents

Revision ID: ba7a5a281de8
Revises: c58de4f6b158
Create Date: 2026-08-04 04:17:58.353367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7a5a281de8'
down_revision: Union[str, Sequence[str], None] = 'c58de4f6b158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('process', sa.Enum('PENDING', 'PROCESS', 'REJECTED', 'DONE', name='processstatus'), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'process')
    # ### end Alembic commands ###
